Repository reservoirprotocol/indexer, pull requests merged in 2022-06, with the labels that each got.

#732 feat: added logic for top bid
  src/jobs/index.ts
  src/jobs/nft-balance-updates/backfill-top-bid-queue.ts
  src/jobs/nft-balance-updates/index.ts
  src/jobs/nft-balance-updates/update-top-bid-queue.ts
  src/jobs/order-updates/by-id-queue.ts
  src/migrations/1643716513646_balances.sql
Labels: api

#849 feat: added logic to avoid duplicate jobs
  src/jobs/activities/process-activity-event.ts
  src/sync/events/index.ts
Labels: feature

#846 Feat/remove buy order events
  src/jobs/index.ts
  src/jobs/order-updates/by-id-queue.ts
  src/jobs/order-updates/index.ts
  src/jobs/order-updates/remove-buy-order-events.ts
Labels: feature

#943 Fix/activities api types
  src/api/endpoints/activities/get-collection-activity/v1.ts
  src/api/endpoints/activities/get-token-activity/v1.ts
  src/api/endpoints/activities/get-user-activity/v1.ts
Labels: fix

#941 Feat/contract wide bids
  src/jobs/bid-updates/index.ts
  src/jobs/bid-updates/top-bid-update-queue.ts
  src/jobs/index.ts
  src/jobs/order-updates/by-id-queue.ts
  src/jobs/order-updates/index.ts
Labels: performance

#982 feat: update timeout response
  src/api/index.ts
Labels: feature

#1029 Feat/rarity
  package.json
  src/api/endpoints/admin/index.ts
  src/api/endpoints/admin/post-calc-rarity.ts
  src/api/endpoints/tokens/get-tokens/v4.ts
  src/api/routes.ts
  src/jobs/collection-updates/index.ts
  src/jobs/collection-updates/rarity-queue.ts
  src/jobs/index.ts
  src/jobs/metadata-index/write-queue.ts
  src/migrations/1643714286947_tokens.sql
  src/scripts/backfill-rarity.ts
  src/utils/rarity.ts
  yarn.lock
Labels: feature
